sudo: false
language: rust
# cache dependencies: https://docs.travis-ci.com/user/caching/#Rust-Cargo-cache
cache: cargo
# run builds for all the trains
rust:
  - stable
  - beta
  - nightly

env:
  global:
    - RUST_BACKTRACE=1

notifications:
  email: false
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
