[package]

name = "colonize"
version = "0.0.1"
authors = [ "Nikita Pekin <contact@nikitapek.in>" ]

[[bin]]

name = "colonize"

[dependencies]
noise = "*"

[dependencies.colonize-backend]
path = "backend"

[dependencies.colonize-utility]
path = "utility"

[dependencies.pistoncore-event]
git = "https://github.com/PistonDevelopers/event"

[dependencies.pistoncore-input]
git = "https://github.com/PistonDevelopers/input"

[dependencies.pistoncore-window]
git = "https://github.com/PistonDevelopers/window"

[dependencies.piston3d-gfx_voxel]
git = "https://github.com/PistonDevelopers/gfx_voxel"

[dependencies.quack]
git = "https://github.com/PistonDevelopers/quack"

[dependencies.tcod_window]
git = "https://github.com/indiv0/tcod_window"
