[package]

name = "colonize"
version = "0.0.2"
authors = [ "Nikita Pekin <contact@nikitapek.in>" ]

[[bin]]

name = "colonize"

[dependencies]
noise = "*"
pistoncore-event = "*"
pistoncore-input = "*"
pistoncore-window = "*"
array = "0.0.0"
quack = "*"
tcod_window = "0.0.3"

[dependencies.colonize-backend]
path = "backend"

[dependencies.colonize-utility]
path = "utility"
