[package]

name = "colonize"
version = "0.0.1"
authors = [ "Nikita Pekin <contact@nikitapek.in>" ]

[[bin]]

name = "colonize"

[dependencies.conrod]
git = "https://github.com/PistonDevelopers/conrod"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.pistoncore-event]
git = "https://github.com/PistonDevelopers/event"

[dependencies.pistoncore-input]
git = "https://github.com/PistonDevelopers/input"

[dependencies.pistoncore-sdl2_window]
git = "https://github.com/PistonDevelopers/sdl2_window.git"

[dependencies.piston2d-graphics]
git = "https://github.com/PistonDevelopers/graphics"

[dependencies.piston2d-opengl_graphics]
git = "https://github.com/PistonDevelopers/opengl_graphics"

[dependencies.quack]
git = "https://github.com/PistonDevelopers/quack"

[dependencies.resources_package]
git = "https://github.com/tomaka/rust-package"

[dependencies.shader_version]
git = "https://github.com/PistonDevelopers/shader_version"
