[package]

name = "colonize"
version = "0.0.1"
authors = [ "Nikita Pekin <contact@nikitapek.in>" ]

[[bin]]

name = "colonize"
path = "src/client.rs"

[dependencies.noise]
git = "https://github.com/bjz/noise-rs"

[dependencies.piston3d-gfx_voxel]
git = "https://github.com/PistonDevelopers/gfx_voxel"

[dependencies.tcod]
git = "https://github.com/tomassedovic/tcod-rs.git"
