[package]

name = "colonize"
version = "0.0.2"
authors = [ "Nikita Pekin <contact@nikitapek.in>" ]

[[bin]]

name = "colonize"

[dependencies]
cgmath = "0.9.1"
tcod_window = "0.2.0"
piston = "0.20.0"

[dependencies.clippy]
optional = true
version = "0.0.63"

[dependencies.colonize_backend]
path = "backend"

[dependencies.colonize_utility]
path = "utility"

[dependencies.colonize_world]
path = "world"

[features]
nightly-testing = [
    "colonize_backend/nightly-testing",
    "colonize_utility/nightly-testing",
    "colonize_world/nightly-testing",
    "clippy",
]
